[model]
n_head = 12
n_embd = 768
d_ff_k = 4
bias = false
dropout = 0.0
n_layer = 12
max_seq_len = 50

[train]
seed = 8723642934
num_epochs = 2
batch_size = 9
target_batch_size = 36
num_workers = 6
learning_rate = 0.001
weight_decay = 0.01
warmup_steps = 350
